# Generated by Django 2.2.7 on 2019-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
